### ISSUE TITLE
T1 Library Missing MyRIO System Include Path 

### ISSUE THREAD

**Issue by CameronDevine** [rtc-book/vm-vagrant#11]
In Eclipse the T1 library is missing the MyRIO system include path, 

```
"${env_var:LIB_PATH}/usr/include"
```

This results in an issue where `IRQConfigure.c` cannot find `<stdio.h>`.

**Comment by ricopicone** [comment]
Is this the issue you mentioned in the meeting today?

**Comment by CameronDevine** [comment]
I believe so.

**Comment by ricopicone** [comment]
So it's also `stdio.h` and not just `stdint.h`? I can look back at the Eclipse settings .... Those settings and how we change them are definitely the most obscure aspects of this project.

**Comment by ricopicone** [comment]
And remind me—it's Lab 3 where this starts?

**Comment by CameronDevine** [comment]
Lab 3 is where I noticed it, but I think it is a problem with the T1 build, which is needed for all labs.
