### ISSUE TITLE
Editor Text

### ISSUE THREAD

**Issue by CameronDevine** [rtc-book/vm-vagrant#3]
The current font in Eclipse isn't great for looking at code. My old VM is using `Courier New` size 10.

To change the font in Eclipse you can go to `Window`->`Preferences` then expand `General` and its subcategory `Appearance`. Under appearance click on `Colors and Fonts`. Next expand the `Basic` category and click on `Text Font`.

**Comment by ricopicone** [comment]
To clarify, Courier New size 10 is your preferred font? I'm wondering if this is fixed with the fix I'm working on for #2

**Comment by CameronDevine** [comment]
Joe mentioned that the font wasn't a good choice earlier today. My guess is he would find the old default acceptable.

**Comment by ricopicone** [comment]
Sounds good -- I checked and the new VM is Courier New size 10, as you mentioned. Must have lost the old defaults in the current build. Once the new distribution is tested, we can close this.

**Comment by ricopicone** [comment]
Fixed in the latest release.
